name: CI
on:
  push:
    branches:
      - '*'
jobs:
  ci:
    runs-on: ubuntu-22.04
    steps:
      - name: Check out
        uses: actions/checkout@v3

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          distribution: zulu
          java-version: 11

      - name: Check
        run: ./gradlew check

      - name: Upload reports
        uses: actions/upload-artifact@v3
        with:
          name: reports
          path: '*/build/reports'
        if: always()
