name: Publish to Maven Central
on:
  release:
    types: [created]
jobs:
  publish:
    runs-on: ubuntu-22
    steps:
      - name: Check out
        uses: actions/checkout@v3

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          distribution: zulu
          java-version: 11

      - name: Check
        run: ./gradlew check --info --stacktrace

      - name: Publish package
        run: ./gradlew publish --info --stacktrace
        env:
          OSSRH_USERNAME: ${{ secrets.OSSRH_USERNAME }}
          OSSRH_TOKEN: ${{ secrets.OSSRH_TOKEN }}
          OSSRH_GPG_KEY: ${{ secrets.OSSRH_GPG_KEY }}
          OSSRH_GPG_PASSWORD: ${{ secrets.OSSRH_GPG_PASSWORD }}

      - name: Upload reports
        uses: actions/upload-artifact@v3
        with:
          name: reports
          path: '*/build/reports'
        if: always()
