name: Publish to Maven Central
on:
  workflow_dispatch:
  push:
    tags:
      - '*.*.*'
permissions:
  contents: read
  pages: write
  id-token: write
concurrency:
  group: "release"
  cancel-in-progress: false
jobs:
  publish:
    runs-on: ubuntu-22.04
    steps:
      - name: Check out
        uses: actions/checkout@v3

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          distribution: zulu
          java-version: 11

      - name: Check
        run: ./gradlew check --info --stacktrace

      - name: Determine version
        run: echo "VERSION=`./gradlew -q printVersion | tail -n 1`" >> $GITHUB_ENV

      - name: Publish package
        run: ./gradlew publish --info --stacktrace
        env:
          OSSRH_USERNAME: ${{ secrets.OSSRH_USERNAME }}
          OSSRH_TOKEN: ${{ secrets.OSSRH_TOKEN }}
          OSSRH_GPG_KEY: ${{ secrets.OSSRH_GPG_KEY }}
          OSSRH_GPG_PASSWORD: ${{ secrets.OSSRH_GPG_PASSWORD }}

      - name: Build docs
        run: |
          ./gradlew dokkaHtmlMultiModule --info --stacktrace
          mkdir -p ./build/pages/apidocs
          cp -r ./build/dokka/htmlMultiModule ./build/pages/apidocs/latest
      - name: Set up GitHub Pages
        uses: actions/configure-pages@v3
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v2
        with:
          path: ./build/pages
      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v2

      - name: Upload reports
        uses: actions/upload-artifact@v3
        with:
          name: reports
          path: '*/build/reports'
        if: always()
