name: Publish to Maven Central
on:
  workflow_dispatch:
  push:
    tags:
      - '*.*.*'
jobs:
  publish:
    runs-on: ubuntu-22.04
    steps:
      - name: Check out
        uses: actions/checkout@v3
        with:
          ref: main
          fetch-depth: 0

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          distribution: zulu
          java-version: 11

      - name: Check
        run: ./gradlew check --info --stacktrace

      - name: Determine version
        run: echo "VERSION=`./gradlew -q printVersion | tail -n 1`" >> $GITHUB_ENV

      - name: Publish package
        run: ./gradlew publish --info --stacktrace
        env:
          OSSRH_USERNAME: ${{ secrets.OSSRH_USERNAME }}
          OSSRH_TOKEN: ${{ secrets.OSSRH_TOKEN }}
          OSSRH_GPG_KEY: ${{ secrets.OSSRH_GPG_KEY }}
          OSSRH_GPG_PASSWORD: ${{ secrets.OSSRH_GPG_PASSWORD }}

      - name: Publish docs
        run: |
          ./gradlew dokkaHtmlMultiModule --info --stacktrace
          git checkout gh-pages
          mkdir -p apidocs
          cp -r build/dokka/htmlMultiModule apidocs/$VERSION
          rm -f apidocs/latest
          ln -s $VERSION apidocs/latest
          git add apidocs/$VERSION apidocs/latest
          git commit -m "Add docs for $VERSION"
          git push

      - name: Upload reports
        uses: actions/upload-artifact@v3
        with:
          name: reports
          path: '*/build/reports'
        if: always()
